### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by cacqw7**
Simple homepage to use as a jumping off point. Shamelessly "inspired" by [Seattle.rb's](http://www.seattlerb.org/) site. :smile:

Feedback and suggestions are welcome!

archrails

### CODE REVIEW

**Comment by cacqw7** [comment]
Just going to go ahead and close this.

**Comment by ZempTime** [comment]
Hey, totally missed this! Thank you so much!

It would be good if we got the logo in there, and thats a good footer to have, too. So once I finally figure out how to point my lacking registrar to heroku, I'll be revisiting this unless you'd like to hop on it first

**Comment by cacqw7** [comment]
No worries! I'll take a stab at it real quick.

**Comment by cacqw7** [comment]
Pushed some fresh changes. 

- Added the logo to the homepage jumbotron
- Added the logo to the navbar
- Added the footer

**Comment by ZempTime** [comment]
This looks great! Pushing it up now

**Comment by ZempTime** [comment]
image of dancing shark

**Pull request merged**
